# Generated by Django 2.2.14 on 2020-07-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200706_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover',
        ),
    ]
