# Generated by Django 2.2.14 on 2020-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
